name: code-quality-check

on:
  workflow_dispatch:
  push:
    branches: [beta, alpha]
  pull_request:
    branches: [beta, alpha]

permissions: read-all

jobs:
  codeql:
    name: Code QL
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: ['javascript']

    steps:
      - name: Checkout repository for code analysis
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579

      - name: Initialize CodeQL
        uses: github/codeql-action/init@d39d5d5c9707b926d517b1b292905ef4c03aa777
        with:
          languages: ${{ matrix.language }}
          queries: security-extended

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@d39d5d5c9707b926d517b1b292905ef4c03aa777

  nodejsscan:
    name: NodeJS Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout the code
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579

      - name: nodejsscan scan
        id: njsscan
        uses: ajinabraham/njsscan-action@7237412fdd36af517e2745077cedbf9d6900d711
        with:
          args: '. --sarif --output results.sarif || true'

      - name: Upload njsscan report
        uses: github/codeql-action/upload-sarif@d39d5d5c9707b926d517b1b292905ef4c03aa777
        with:
          sarif_file: results.sarif
