name: CodeQL

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 12 * * 4'

permissions: read-all

jobs:
  codeql:
    name: Code QL
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository for code analysis
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Initialize CodeQL
        uses: github/codeql-action/init@4238421316c33d73aeea2801274dd286f157c2bb
        with:
          languages: javascript
          queries: security-extended

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@4238421316c33d73aeea2801274dd286f157c2bb
