name: Cypress QA

on: [push]

permissions: read-all

jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository for cypress tests
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Cypress Run E2E Tests and record
        uses: cypress-io/github-action@be2de7b1fe1cdafb4a3c8da0a3746476ef636b65
        with:
          build: npm run build
          start: npm run preview
          browser: chrome
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_LMM_OA_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
