name: DEV-to-PROD

on:
  workflow_dispatch:

permissions: read-all

jobs:
  dev_to_prod:
    name: Rebase from development to production
    environment:
      name: Production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout for rebase preparation
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Do git rebase
        run: |
          git fetch --all
          git rebase --onto origin/alpha main
          git push -f origin main
