name: NodeJSScan

on:
  push:
    branches: [alpha]
  pull_request:
    branches: [alpha]
  schedule:
    - cron: '0 12 * * 4'

permissions: read-all

jobs:
  nodejsscan:
    name: NodeJS Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout the code
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846

      - name: nodejsscan scan
        id: njsscan
        uses: ajinabraham/njsscan-action@7237412fdd36af517e2745077cedbf9d6900d711
        with:
          args: '. --sarif --output results.sarif || true'

      - name: Upload njsscan report
        uses: github/codeql-action/upload-sarif@1ed1437484560351c5be56cf73a48a279d116b78
        with:
          sarif_file: results.sarif
