name: NodeJSScan

on:
  push:
    branches: [alpha]
  pull_request:
    branches: [alpha]
  schedule:
    - cron: '0 12 * * 4'

permissions: read-all

jobs:
  nodejsscan:
    name: NodeJS Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout the code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: nodejsscan scan
        id: njsscan
        uses: ajinabraham/njsscan-action@d58d8b2f26322cd35a9efb8003baac517f226d81
        with:
          args: '. --sarif --output results.sarif || true'

      - name: Upload njsscan report
        uses: github/codeql-action/upload-sarif@904260d7d935dff982205cbdb42025ce30b7a34f
        with:
          sarif_file: results.sarif
