name: PROD-to-DEV

on:
  workflow_dispatch:

permissions: read-all

jobs:
  prod_to_dev:
    name: Rebase from production to development and release
    environment:
      name: Development
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout for rebase preparation
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Do git rebase
        run: |
          git fetch --all
          git checkout alpha
          git rebase --onto origin/main alpha
          git push -f origin alpha

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install package dependencies
        run: npm ci

      - name: Rebuild App
        run: npm run build

      - name: Check if new version has been generated
        id: check_build
        uses: andstor/file-existence-action@87d74d4732ddb824259d80c8a508c0124bf1c673
        with:
          files: 'build'

      - name: Deploy to Firebase
        if: ${{ steps.check_build.outputs.files_exists == 'true' }}
        uses: doonstore/firebase-deploy@3c07a0714007ef3bec30f35ed62f43b13cf48ad5
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: ${{ secrets.FIREBASE_PROJECT }}
