name: PROD-to-DEV

on:
  workflow_dispatch:

permissions: read-all

jobs:
  prod_to_dev:
    name: Rebase from production to development
    environment:
      name: Development
    runs-on: ubuntu-latest

    steps:
      - name: Checkout for rebase preparation
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Do git rebase
        run: |
          git fetch --all
          git checkout release-alpha
          git rebase --onto origin/main release-alpha
          git push -f origin release-alpha
