name: CD-Re

on:
  workflow_dispatch:

permissions: read-all

jobs:
  redeploy_dev:
    name: Rebuild and Deploy to Production
    if: ${{ github.repository == 'sws2apps/lmm-oa-sws' && github.ref == 'refs/heads/main' }}
    environment:
      name: Prod.env
      url: https://lmm-oa-sws.web.app
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout for release preparation
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
        with:
          ref: main
          persist-credentials: false

      - name: Use Node.js current version
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
        with:
          node-version: current

      - name: Install package dependencies
        run: npm ci

      - name: Rebuild App
        run: npm run build
        env:
          VITE_FINGERPRINT_API_CLIENT_KEY: ${{ secrets.VITE_FINGERPRINT_API_CLIENT_KEY }}

      - name: Check if new version has been generated
        id: check_build
        uses: andstor/file-existence-action@20b4d2e596410855db8f9ca21e96fbe18e12930b
        with:
          files: 'dist'

      - name: Deploy to Firebase
        if: ${{ steps.check_build.outputs.files_exists == 'true' }}
        uses: sws2apps/firebase-deployment@8bd00ef2c7fb6feb0c092f38287f00a652e0ee34
        with:
          workloadIdentityProvider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          serviceAccount: ${{ secrets.SERVICE_ACCOUNT }}
          project: lmm-oa-sws
