name: CD-Re

on:
  workflow_dispatch:

permissions: read-all

jobs:
  redeploy_dev:
    name: Rebuild and Deploy to Production
    if: ${{ github.repository == 'sws2apps/lmm-oa-sws' && github.ref == 'refs/heads/main' }}
    environment:
      name: Prod.env
      url: https://lmm-oa-sws.web.app
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout for release preparation
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          ref: main
          persist-credentials: false

      - name: Use Node.js current version
        uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93
        with:
          node-version: current

      - name: Install package dependencies
        run: npm ci

      - name: Rebuild App
        run: npm run build

      - name: Check if new version has been generated
        id: check_build
        uses: andstor/file-existence-action@f02338908d150e00a4b8bebc2dad18bd9e5229b0
        with:
          files: 'build'

      - name: Deploy to Firebase
        if: ${{ steps.check_build.outputs.files_exists == 'true' }}
        uses: sws2apps/firebase-deployment@8bd00ef2c7fb6feb0c092f38287f00a652e0ee34
        with:
          workloadIdentityProvider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          serviceAccount: ${{ secrets.SERVICE_ACCOUNT }}
          project: lmm-oa-sws
