name: CD-Re

on:
  workflow_dispatch:

permissions: read-all

jobs:
  redeploy_dev:
    name: Rebuild and Deploy to Development
    if: ${{ github.repository == 'sws2apps/lmm-oa-sws' && github.ref == 'refs/heads/alpha' }}
    environment:
      name: Development
      url: https://dev-lmm-oa-sws.web.app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout for release preparation
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          ref: alpha
          persist-credentials: false

      - name: Use Node.js current version
        uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93
        with:
          node-version: current

      - name: Install package dependencies
        run: npm ci

      - name: Rebuild App
        run: npm run build

      - name: Check if new version has been generated
        id: check_build
        uses: andstor/file-existence-action@f02338908d150e00a4b8bebc2dad18bd9e5229b0
        with:
          files: 'build'

      - name: Deploy to Firebase
        if: ${{ steps.check_build.outputs.files_exists == 'true' }}
        uses: sws2apps/firebase-deployment@8bd00ef2c7fb6feb0c092f38287f00a652e0ee34
        with:
          project: dev-lmm-oa-sws
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

